// 결 · GYEOL — 8관 32작품 메타데이터
// main.js·selftest.js가 소비한다. WORKS의 id는 작품 파일명 `w{wing}-{id}.js`와 일치해야 한다.

export const WINGS = [
  { no:1, id:'mukhyang', name:'묵향', hanja:'墨', tagline:'수묵의 물성',
    desc:'먹이 번지고, 붓이 지나가고, 안개가 산을 삼킨다. 수묵의 물성을 코드로 옮겼다.' },
  { no:2, id:'obang', name:'오방', hanja:'五方', tagline:'색과 문양',
    desc:'청·백·적·흑·황 다섯 방위의 빛깔로 문양이 피어난다. 오방색이 이루는 질서와 놀이.' },
  { no:3, id:'hunmin', name:'훈민', hanja:'訓民', tagline:'글자의 기하학',
    desc:'한글의 자모가 입자와 별과 물살이 된다. 글자에 깃든 기하학을 풀어낸다.' },
  { no:4, id:'yeobaek', name:'여백', hanja:'餘白', tagline:'비움의 미학',
    desc:'달항아리와 백자, 보름달과 숨. 채우지 않아 오히려 가득 차는 여백의 미학.' },
  { no:5, id:'jogakbo', name:'조각보', hanja:'', tagline:'우연의 기하학',
    desc:'남은 천 조각이 만나 뜻밖의 무늬를 이룬다. 우연이 짓는 기하학의 아름다움.' },
  { no:6, id:'pungnyu', name:'풍류', hanja:'風流', tagline:'소리의 형상',
    desc:'사물놀이와 오음, 목소리와 산조. 소리가 눈에 보이는 형상으로 번진다.' },
  { no:7, id:'minhwa', name:'민화', hanja:'民畫', tagline:'다시 그린 옛 그림',
    desc:'일월오봉도와 호작도, 십장생과 어변성룡. 옛 민화를 코드로 다시 그린다.' },
  { no:8, id:'sesi', name:'세시', hanja:'歲時', tagline:'시간을 새기다',
    desc:'절기와 물시계, 달의 위상과 십이지. 흐르는 시간을 화면에 새긴다.' },
];

export const WORKS = [
  // 1관 묵향
  { id:'balmuk', wing:1, title:'발묵', en:'Bleeding Ink',
    desc:'화선지에 먹이 스며들 듯, 터치한 자리에서 먹이 번져 나간다.',
    how:'터치/드래그로 먹을 떨어뜨리세요. 느리게 그으면 굵고 짙게 고이고, 빠르게 그으면 가늘게 갈라지는 갈필이 됩니다.', needs:[] },
  { id:'ilpil', wing:1, title:'일필', en:'One Stroke',
    desc:'한 번의 붓질 안에 갈필과 윤필이 함께 산다. 손이 지나간 궤적이 그대로 획이 된다.',
    how:'드래그로 붓을 끄세요. 속도가 갈필과 윤필을 가르고, 꾹 누르면 먹이 스며 번집니다.', needs:[] },
  { id:'ujung', wing:1, title:'우중산수', en:'Mountains in Rain',
    desc:'안개가 산을 삼켰다 다시 내어놓는다. 비 내리는 산수의 깊이가 시점을 따라 겹겹이 열린다.',
    how:'기기를 기울이면 시점이 움직입니다. 데스크톱에서는 마우스로 대신합니다.', needs:['gyro'] },
  { id:'mukjuk', wing:1, title:'묵죽', en:'Ink Bamboo',
    desc:'자라난 먹빛 대숲이 바람에 흔들린다. 마디마디 붓끝의 떨림이 배어 있다.',
    how:'마이크에 바람을 불어 보세요. 세게 불수록 댓잎이 크게 흔들립니다.', needs:['mic'] },

  // 2관 오방
  { id:'dancheong', wing:2, title:'단청 만다라', en:'Dancheong Mandala',
    desc:'연화문과 당초문이 대칭으로 피어나 만다라를 이룬다. 단청의 오방색이 끝없이 자기를 반복한다.',
    how:'중심을 터치해 문양을 다시 피우세요.', needs:[] },
  { id:'obangjin', wing:2, title:'오방진', en:'Five-Color Formation',
    desc:'청·백·적·흑·황 오방색 입자가 진법을 이루며 모이고 흩어진다.',
    how:'터치한 곳으로 오방색 입자가 모여듭니다.', needs:[] },
  { id:'saekdong', wing:2, title:'색동', en:'Saekdong Ribbons',
    desc:'색동저고리의 띠처럼, 오색 리본이 물결지어 흐른다.',
    how:'드래그로 색동 물결을 일으키세요.', needs:[] },
  { id:'nakhwa', wing:2, title:'낙화', en:'Falling Petals',
    desc:'꽃잎이 중력을 따라 흩날린다. 기울기마다 바람의 방향이 바뀐다.',
    how:'기기를 기울이면 바람이 바뀝니다. 데스크톱에서는 마우스로 대신합니다.', needs:['gyro'] },

  // 3관 훈민
  { id:'jamo', wing:3, title:'자모 우주', en:'Jamo Cosmos',
    desc:'흩어진 입자가 모여 한글 자모가 되었다가, 다시 별처럼 흩어진다.',
    how:'터치하면 자모가 흩어졌다 다시 모입니다.', needs:[] },
  { id:'gang', wing:3, title:'글자의 강', en:'River of Letters',
    desc:'써 넣은 글자가 물살을 타고 흘러내린다. 문장이 강이 되어 굽이친다.',
    how:'글자를 입력하면 강물처럼 흘러갑니다.', needs:[] },
  { id:'jeongeum', wing:3, title:'정음 별자리', en:'Jeongeum Constellation',
    desc:'손끝을 이으면 자모가 별자리로 맺힌다. 훈민정음의 획이 밤하늘에 걸린다.',
    how:'손을 들어 자모를 이어 별자리를 그리세요.', needs:['hands'] },
  { id:'hwalja', wing:3, title:'활자 비', en:'Type Rain',
    desc:'한글 활자가 비처럼 쏟아져 쌓인다. 낱글자가 모여 소나기를 이룬다.',
    how:'터치한 자리로 활자 비가 쏟아집니다.', needs:[] },

  // 4관 여백
  { id:'dalhangari', wing:4, title:'달항아리', en:'Moon Jar',
    desc:'물레가 돌아 달항아리가 빚어진다. 소리의 크기가 그 부풂과 여백을 정한다.',
    how:'마이크에 소리를 내면 항아리가 부풀어 오릅니다.', needs:['mic'] },
  { id:'bingnyeol', wing:4, title:'빙렬', en:'Crackle Glaze',
    desc:'백자 유약의 빙렬이 실금을 그리며 번져 나간다. 균열마저 무늬가 된다.',
    how:'터치한 자리에서 균열이 뻗어 나갑니다.', needs:[] },
  { id:'boreumdal', wing:4, title:'보름달', en:'Full Moon',
    desc:'구름 사이로 달이 차고 기운다. 비움과 채움 사이에서 보름달이 떠오른다.',
    how:'드래그로 구름을 걷어 달을 드러내세요.', needs:[] },
  { id:'sum', wing:4, title:'숨', en:'Breath',
    desc:'텅 빈 화면이 천천히 부풀고 잦아든다. 여백이 숨을 쉰다.',
    how:'가만히 바라보거나 터치하면 여백이 크게 숨을 들이쉽니다.', needs:[] },

  // 5관 조각보
  { id:'jogakbo', wing:5, title:'조각보', en:'Patchwork Wrapping',
    desc:'남은 천 조각이 우연히 만나 하나의 보자기가 된다. 조각마다 다른 결이 어우러진다.',
    how:'클릭하면 조각보가 다시 짜입니다.', needs:[] },
  { id:'homjil', wing:5, title:'홈질', en:'Running Stitch',
    desc:'한 땀 한 땀 홈질이 이어져 길을 낸다. 바늘땀이 선이 되어 화면을 가로지른다.',
    how:'드래그한 경로를 따라 홈질이 놓입니다.', needs:[] },
  { id:'nobang', wing:5, title:'노방', en:'Sheer Silk',
    desc:'반투명한 노방이 겹칠 때마다 새로운 색이 태어난다.',
    how:'드래그로 노방을 겹쳐 색을 섞으세요.', needs:[] },
  { id:'maedeup', wing:5, title:'매듭', en:'Knot',
    desc:'끈이 당겨지고 얽히며 매듭을 짓는다. 팽팽함과 느슨함이 매듭의 모양을 정한다.',
    how:'드래그로 끈을 당겨 매듭을 지으세요.', needs:[] },

  // 6관 풍류
  { id:'samulnori', wing:6, title:'사물놀이', en:'Samulnori',
    desc:'꽹과리·징·장구·북의 가락이 입자의 타격으로 터진다. 소리가 곧 형상이 된다.',
    how:'마이크로 소리를 내면 리듬이 입자로 튑니다.', needs:['mic'] },
  { id:'oeum', wing:6, title:'오음', en:'Five Tones',
    desc:'궁·상·각·치·우 다섯 소리가 색과 결로 번진다. 오음계의 사운드스케이프가 화면에 퍼진다.',
    how:'화면을 터치해 오음을 울리세요.', needs:[] },
  { id:'cheong', wing:6, title:'청', en:'Voice Scroll',
    desc:'목소리가 파동이 되어 두루마리처럼 풀려 나간다. 말이 곧 그림이 된다.',
    how:'마이크에 목소리를 내면 파동이 그려집니다.', needs:['mic'] },
  { id:'sanjo', wing:6, title:'산조', en:'Sanjo',
    desc:'진양조에서 자진모리로, 가락이 스스로 짜여 흐른다. 산조의 흐름이 선율로 피어난다.',
    how:'터치하면 새로운 가락이 풀려 나옵니다.', needs:[] },

  // 7관 민화
  { id:'ilwol', wing:7, title:'일월오봉도', en:'Sun, Moon and Five Peaks',
    desc:'해와 달, 다섯 봉우리가 하루의 시간을 따라 물든다. 왕의 병풍이 셰이더 빛으로 되살아난다.',
    how:'시간대에 따라 하늘빛이 변합니다. 터치로 해와 달을 옮기세요.', needs:['webgl'] },
  { id:'hojakdo', wing:7, title:'호작도', en:'Tiger and Magpie',
    desc:'반응확산이 자라며 호랑이의 줄무늬를 그린다. 까치가 그 위에 소식을 얹는다.',
    how:'터치한 자리에서 호랑이 무늬가 번져 자랍니다.', needs:[] },
  { id:'sipjangsaeng', wing:7, title:'십장생', en:'Ten Longevities',
    desc:'학 무리가 떼 지어 날며 십장생의 하늘을 그린다.',
    how:'커서를 따라 학 무리가 방향을 바꿉니다.', needs:[] },
  { id:'eobyeon', wing:7, title:'어변성룡', en:'Carp Becomes Dragon',
    desc:'잉어 떼가 물살을 거슬러 오르다 용오름으로 솟는다. 등용문의 순간이 펼쳐진다.',
    how:'드래그로 물살을 만들면 잉어가 거슬러 오릅니다.', needs:[] },

  // 8관 세시
  { id:'seumulnet', wing:8, title:'스물넷', en:'Twenty-Four Terms',
    desc:'입춘에서 대한까지, 스물네 절기가 실시간으로 돌아간다. 오늘이 어느 절기에 닿아 있는지 새긴다.',
    how:'지금 시각의 절기가 나타납니다. 터치로 한 해를 돌려 보세요.', needs:[] },
  { id:'jagyeongnu', wing:8, title:'자격루', en:'Water Clock',
    desc:'물방울이 떨어져 시각을 재던 자격루. 물의 무게로 시간이 흘러내린다.',
    how:'터치하면 물방울이 떨어져 시간을 잽니다.', needs:[] },
  { id:'dalgeurimja', wing:8, title:'달그림자', en:'Moon Shadow',
    desc:'음력을 따라 달이 차고 기울며 그림자를 드리운다.',
    how:'드래그로 달의 위상을 넘겨 보세요.', needs:[] },
  { id:'sibiji', wing:8, title:'십이지', en:'Twelve Guardians',
    desc:'자시에서 해시까지, 열두 지신이 시간의 문양으로 돈다. 손짓이 시각을 불러낸다.',
    how:'손을 들어 열두 지신의 시각을 짚으세요.', needs:['hands'] },
];

export const wingWorks = (no) => WORKS.filter(w => w.wing === no);
